# build react app, it should be /build
# FROM node:12.2.0-alpine as build
FROM node:14-alpine as build
WORKDIR /app
COPY package.json /app/package.json
RUN npm install --only=prod
COPY . /app
RUN npm run build


FROM nginx:stable-alpine as production-stage
RUN mkdir /app
COPY --from=build /app/.next /app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

